FROM jlesage/baseimage-gui:ubuntu-22.04-v4@sha256:996a6e6c024c52cce5d0447ccb26fd0d6bdeeff9fdd58c303438c4e29081c654

RUN apt-get update

RUN apt-get install -y curl software-properties-common gnupg2 winbind xvfb

RUN dpkg --add-architecture i386
RUN curl -O https://dl.winehq.org/wine-builds/winehq.key
RUN apt-key add winehq.key
RUN add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ jammy main'
RUN apt-get update
RUN apt-get install -y winehq-stable

RUN apt-get install -y winetricks

RUN apt-get clean -y && apt-get autoremove -y

ENV WINEPREFIX /config/wine/
    
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

ENV LANG en_US.UTF-8

ENV APP_NAME="Backblaze Personal Backup"

# Disable WINE Debug messages
ENV WINEDEBUG -all

EXPOSE 5900

COPY startapp.sh /startapp.sh
RUN chmod +x /startapp.sh