FROM jlesage/baseimage-gui:alpine-3.20-v4.6.1@sha256:15c6f519f20efe16d789b700c09e876798a97b84eb49663fbb7228364571afda

ENV WINEPREFIX /config/wine/
ENV APP_NAME="Backblaze Personal Backup"
ENV FORCE_LATEST_UPDATE="true"
ENV DISABLE_AUTOUPDATE="true"
ENV DISABLE_VIRTUAL_DESKTOP="true"
ENV DISPLAY_WIDTH="900"
ENV DISPLAY_HEIGHT="700"
# Disable WINE Debug messages
ENV WINEDEBUG -all
# Set DISPLAY to allow GUI programs to be run
ENV DISPLAY=:0

RUN apk update && \
    apk add --no-cache \
        curl \
        wine=9.0-r0 \
        samba \
        xvfb \
        dpkg \
        dpkg \
    && apk add --no-cache --virtual .build-deps \
    && curl -Lo /usr/local/bin/winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks \
    && chmod +x /usr/local/bin/winetricks \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/*

COPY rootfs/ /
RUN chmod +x /startapp.sh