FROM jlesage/baseimage-gui:alpine-3.20-v4.6.4@sha256:bc47da3cc4439679e338f9c87d71cbec658485ab564280fb210a6c36af4b128d

ENV WINEPREFIX /config/wine/
ENV APP_NAME="Backblaze Personal Backup"
ENV FORCE_LATEST_UPDATE="true"
ENV DISABLE_AUTOUPDATE="true"
ENV DISABLE_VIRTUAL_DESKTOP="true"
ENV DISPLAY_WIDTH="900"
ENV DISPLAY_HEIGHT="700"
# Disable WINE Debug messages
ENV WINEDEBUG -all
# Set DISPLAY to allow GUI programs to be run
ENV DISPLAY=:0

RUN apk update && \
    apk add --no-cache \
        curl \
        wine=9.0-r0 \
        samba \
        xvfb \
        dpkg \
        dpkg \
    && apk add --no-cache --virtual .build-deps \
    && curl -Lo /usr/local/bin/winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks \
    && chmod +x /usr/local/bin/winetricks \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/*

COPY rootfs/ /
RUN chmod +x /startapp.sh